package com.example.zenithevents.HelperClasses;
import android.util.Log;

import com.example.zenithevents.Objects.Facility;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.ListenerRegistration;

import java.util.ArrayList;
import java.util.List;

/*
 * This class was generated by ChatGpt
 */

public class FirestoreFacilitiesCollection {
    public interface FetchFacilitiesCallback {
        void onCallback(List<Facility> facilityList);
    }

    public interface FetchFacilityCallback {
        void onCallback(Facility facility);
    }

    private static ListenerRegistration collectionListenerRegistration;
    private static ListenerRegistration documentListenerRegistration;

    // Listen to changes in the entire "facilities" collection
    public static void listenForFacilityCollectionChanges(FetchFacilitiesCallback callback) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();

        collectionListenerRegistration = db.collection("facilities")
                .addSnapshotListener((querySnapshot, e) -> {
                    if (e != null) {
                        Log.e("Firestore", "Collection listen failed.", e);
                        callback.onCallback(null);
                        return;
                    }

                    List<Facility> facilityList = new ArrayList<>();
                    if (querySnapshot != null) {
                        for (DocumentSnapshot document : querySnapshot.getDocuments()) {
                            Facility facility = document.toObject(Facility.class);
                            facilityList.add(facility);
                        }
                    }
                    callback.onCallback(facilityList);
                });
    }

    // Listen to changes in a specific facility document by ID
    public static void listenForSpecificFacilityChanges(String facilityId, FetchFacilityCallback callback) {
        FirebaseFirestore db = FirebaseFirestore.getInstance();

        documentListenerRegistration = db.collection("facilities")
                .document(facilityId)
                .addSnapshotListener((documentSnapshot, e) -> {
                    if (e != null) {
                        Log.e("Firestore", "Document listen failed.", e);
                        callback.onCallback(null);
                        return;
                    }

                    if (documentSnapshot != null && documentSnapshot.exists()) {
                        Facility facility = documentSnapshot.toObject(Facility.class);
                        callback.onCallback(facility);
                    } else {
                        callback.onCallback(null); // Document does not exist
                    }
                });
    }

    // Stop listening to changes in the "facilities" collection
    public static void stopListeningForFacilityCollectionChanges() {
        if (collectionListenerRegistration != null) {
            collectionListenerRegistration.remove();
            collectionListenerRegistration = null;
        }
    }

    // Stop listening to changes in a specific facility document
    public static void stopListeningForSpecificFacilityChanges() {
        if (documentListenerRegistration != null) {
            documentListenerRegistration.remove();
            documentListenerRegistration = null;
        }
    }
}
